Feat/employer evaluation
thomas-mauran/LinkedOut pull request #45
Opened 2023-12-31 18:01 UTC by thomas-mauran

![image](https://github.com/thomas-mauran/LinkedOut/assets/78204354/63a5ac0f-7c99-4a7c-94e3-ff8918b2eaf3)

- fix on messaging app bar
- evaluation of an employer

2024-01-01 12:19 UTC, Kuruyia requested changes

2024-01-01 12:19 UTC, Kuruyia commented on front/src/components/utils/StarRatingSelector.tsx
Maybe replace our `StarRating` component with this component so we don't have two similar things. We can pass a `readonly` prop to know if the rating should be able to be updated.

2024-01-01 12:19 UTC, Kuruyia commented on front/src/pages/employer/EmployerEvaluationPage.tsx
> +    useGetEmployerQuery(employerId); // Replace '123' with the actual employer ID
```suggestion
    useGetEmployerQuery(employerId);
```

2024-01-01 22:53 UTC, thomas-mauran commented on front/src/components/utils/StarRatingSelector.tsx
done

2024-01-01 22:53 UTC, thomas-mauran commented on front/src/pages/employer/EmployerEvaluationPage.tsx
> +    useGetEmployerQuery(employerId); // Replace '123' with the actual employer ID
done

2024-01-02 06:14 UTC, Kuruyia approved these changes

2024-01-02 18:20 UTC, merged