feat: boostrap of neo4j and simple query
thomas-mauran/LinkedOut pull request #47
Opened 2024-01-16 18:55 UTC by thomas-mauran

boostrap of neo4j

2024-01-16 19:12 UTC, Kuruyia requested changes

2024-01-16 19:12 UTC, Kuruyia commented on backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/RecommendationController.kt
> +        println("HERE")
```suggestion
```

2024-01-16 19:12 UTC, Kuruyia commented on backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/RecommendationService.kt
> +private fun convertJobOfferFromProto(source: JobOfferOuterClass.JobOffer): JobOffer {
Where is this used?

2024-01-16 19:12 UTC, Kuruyia commented on backend/protobuf/src/main/proto/request.proto
> +    services.GetRecommendationRequest get_user_recommendation = 57;
```suggestion
    services.GetRecommendationRequest get_recommendation_request = 57;
```

2024-01-16 21:33 UTC, thomas-mauran commented on backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/RecommendationService.kt
> +private fun convertJobOfferFromProto(source: JobOfferOuterClass.JobOffer): JobOffer {
unused removed

2024-01-17 09:06 UTC, Kuruyia approved these changes

2024-01-17 18:47 UTC, merged