docs: creation of the TAD
thomas-mauran/LinkedOut pull request #74
Opened 2024-02-22 07:35 UTC by thomas-mauran

This pr goal is to write the TAD document to conclude our microservice projet

2024-02-22 09:20 UTC, Kuruyia requested changes
Looks pretty good to me so far!

I can't really think of anything more to add to this than what's already planned (maybe something about the mobile app?). In the end, we could perhaps also add the "What went right?", "What went wrong?", "How can we ensure repeating what went right?" and "How can we avoid repeating what went wrong?" points, but I'm leaving that to your discretion.

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +The Profile Service is responsible for managing user profiles within the LinkedOut platform. It handles the creation, retrieval, and modification of user profiles, as well as the management of user e
```suggestion
The Profile Service is responsible for managing user profiles within the LinkedOut platform. It handles the creation, retrieval, and modification of user profiles, as well as the management of user experiences, evaluation, and availability. 

This service also has to contact the recommendation service whenever a new user is created to store a Neo4j node with their UUID to then later recommend special job offers for this user.
```

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +Like in the job service we populate the database with the job categories, job offers and jobs. To do so we use a [cypher script](./backend/recommendation/) and a neo4j plugin named APOC (Awesome Proc
```suggestion
Like in the job service, we populate the database with the job categories, job offers and jobs. To do so, we use a [Cypher script](./backend/recommendation/) and a Neo4j plugin named APOC (Awesome Procedures On Cypher), which provides a set of procedures and functions to enhance the capabilities of Neo4j.
```

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +![microservices](./docs/ms.png)
```suggestion
![Architecture of the platform](./docs/ms.png)
```

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +![graph db picture](./docs/assets/graph-db-1.png)
```suggestion
![Graph database visualization](./docs/assets/graph-db-1.png)
```

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +In the picture above you can see the graph database after initialization. In red you see each job nodes, in yellow each job category and in blue each job offer nodes.
```suggestion
In the picture above, you can see the graph database after initialization: in red there's each job node, in yellow each job category node and in blue each job offer node.
```

2024-02-22 09:20 UTC, Kuruyia commented on README.md
> +![graph db picture](./docs/assets/graph-db-2.png)
```suggestion
When a new user profile is created, the Recommendation Service stores the user profile as a new node in the Neo4j graph database containing only its ID. Same thing when a new experience is created: we create a new node with the experience ID and link it to both a user node and a job. 

By doing so we have a graph of users, experiences, jobs and job offers. We then use the Neo4j driver to retrieve the recommendations. We use the graph database to find the shortest path between the user and the job offer. We then return a list of job offers IDs. This list of job offers IDs is then used to retrieve the job offers from the job service. If there is no job offers to return, the job service will return all the job offers in the database.

![Graph database visualization](./docs/assets/graph-db-2.png)
```

2024-02-22 18:36 UTC, thomas-mauran commented
> Looks pretty good to me so far!
> 
> I can't really think of anything more to add to this than what's already planned (maybe something about the mobile app?). In the end, we could perhaps also add the "What went right?", "What went wrong?", "How can we ensure repeating what went right?" and "How can we avoid repeating what went wrong?" points, but I'm leaving that to your discretion.

Great Idea gonna work in that way

2024-02-27 10:50 UTC, Kuruyia requested changes

2024-02-27 10:50 UTC, Kuruyia commented on docs/tad.md
> +We chose to deploy our microservices architecture on a Kubernetes cluster to take advantage of its container orchestration capabilities, scalability, and resilience and to improve our understanding o
```suggestion
We chose to deploy our microservices architecture on a Kubernetes cluster to take advantage of its container orchestration capabilities, scalability, and resilience and to improve our understanding of this tool. The production environment is deployed on a k3s cluster hosted on a Proxmox virtual machine at Polytech. We used Kustomize to manage the configuration of the different services and to make the deployment easier.
```

2024-02-27 10:50 UTC, Kuruyia commented on docs/tad.md
> +The Message Service is responsible for managing messages and message channels within the LinkedOut platform. It handles the creation and retrieval of messages and message channels. By doing so, it al
Describe a bit more this section: what is a message channel? how to create them?

2024-02-27 10:50 UTC, Kuruyia commented on docs/tad.md
> +Overall, the project was a success. We learned a lot about microservices, kubernetes, keycloak, neo4j, NATS, protobuf, and many other technologies. We also learned a lot about the importance of organ
```suggestion
Overall, the project was a success. We learned a lot about microservices, Kubernetes, Keycloak, Neo4j, NATS, Protocol Buffers, and many other technologies. We also learned a lot about the importance of organization in general and how to prepare a project the right way by planning it.
```

2024-02-27 10:50 UTC, Kuruyia commented on docs/tad.md
> +Having a good view of the project before it starts is a key point. This is done by defining the Open API, by creating detailed models of the application. Doing this allows us to enlighten all the pot
```suggestion
Having a good view of the project before it starts is a key point. This is done by defining the OpenAPI specification, by creating detailed models of the application. Doing this allows us to enlighten all the potential dark spots of the projects and to make sure if we work in a team that we have a same definition of done for each feature.
```

2024-02-28 17:18 UTC, merged